[package]
name = "fc-macros"
version = "0.1.0"
authors = ["Jonathan Kelley <>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = {version="1.0.37", features=["full"]}
quote = "1.0.7"
heck = "0.3"
